### PR TITLE
Fix build under new gcc

### PR DESCRIPTION
**Pull request by k-bx**
Fixes https://github.com/dfoxfranke/haskell-cld2/issues/1

### CODE REVIEW

**Comment by dfoxfranke** [comment]
I've merged your pull request, but I'm not really maintaining this project any more since the thing I originally needed it for didn't happen. Would you like me to transfer ownership to you?

**Comment by k-bx** [comment]
@dfoxfranke I would love that, yes. Can you also add me to the maintainers list on Hackage so that I can upload new releases? My username there is `k_bx`

**Comment by dfoxfranke** [comment]
Done.

**Comment by k-bx** [comment]
@dfoxfranke one last thing. Can you please go into https://travis-ci.org/dfoxfranke/haskell-cld2 and enable this repo? I've added the travis yaml conf, so it should work on all PRs automatically after that.

**Pull request merged**
